CREATE TABLE IF NOT EXISTS Student (
 ROLL_NO TEXT PRIMARY KEY,
 Name TEXT NOT NULL,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER
);
 

 INSERT INTO Student(ROLL_NO,NAME,ADDRESS,PHONE,AGE) VALUES
 ('1','RAM','DELHI','****',18),
 ('2','RAMESH','GURGAON','****',18),
 ('3','SUJIT','ROHTOK','****',20),
 ('4','SURESH','DELHI','****',18),
 ('5','AMAN','ROHTOK','****',20),
 ('6','HARSH','GURAGOAN','****',18);

SELECT * FROM Student;

SELECT * FROM Student WHERE AGE = 18 AND ADDRESS = 'DELHI';

SELECT * FROM Student WHERE NAME = 'RAM' AND AGE = 18;